#!/usr/bin/env python3

#dalle
resolution = '1024x1024'
number_imgs = 1
#gpt writer
poem_tokens = 700
painter_list = ["Vincent van Gogh", "Gustave Courbet", "Grant Wood", "Leonardo da Vinci", "Jacques-Louis David", "Sandro Botticelli", "Henri Matisse", "Peter Paul Rubens", "Pierre-Auguste Renoir", "Johannes Vermeer", "Edvard Munch", "Salvador Dali"]
#painter_list = ["Vincent van Gogh", "Cyberpunk"]
#user poem description file
user_description_input_filename ="descriptions.txt"
#storage location: poem store fileanme extension
poem_extension="_poem.txt"
#storage locatino: poem description of a poem for an image generated by chatgpt
poem_description_extension="_poemdesc.txt"
#use borker chatgpt to request a description of an image of a poem
use_poem_description = True

def get_prompt():
    return resolution, number_imgs